import { dirname, join } from "node:path";
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { parseFrontmatter } from "../integration/shared/frontmatter";
import type { Skill } from "../execution/features/skills/types";
import type { SkillMcpConfig } from "../execution/features/skill-mcp-manager/types";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SKILLS_DIR = join(__dirname, "../execution/features/skills");
const OUTPUT_FILE = join(__dirname, "../execution/features/skills/skills-manifest.ts");

interface SkillFrontmatter {
  name: string;
  description: string;
  allowedTools?: string[];
  mcpConfig?: SkillMcpConfig;
}

function loadSkillFromDir(dirName: string): Skill | null {
  const skillDir = join(SKILLS_DIR, dirName);
  const skillMdPath = join(skillDir, "SKILL.md");
  if (!existsSync(skillMdPath)) return null;

  const content = readFileSync(skillMdPath, "utf-8");
  const { data, body } = parseFrontmatter<SkillFrontmatter>(content);

  const frontmatter = data ?? ({} as Partial<SkillFrontmatter>);
  const name = frontmatter.name ?? dirName;
  const description = frontmatter.description ?? "";

  return {
    name,
    description,
    template: body.trim(),
    ...(frontmatter.allowedTools ? { allowedTools: frontmatter.allowedTools } : {}),
    ...(frontmatter.mcpConfig ? { mcpConfig: frontmatter.mcpConfig } : {}),
  };
}

function discoverSkills(): Skill[] {
  const entries = readdirSync(SKILLS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right));

  const skills: Skill[] = [];
  const seen = new Set<string>();

  for (const dirName of entries) {
    const skill = loadSkillFromDir(dirName);
    if (!skill) continue;
    if (seen.has(skill.name)) {
      throw new Error(`Duplicate skill name discovered: ${skill.name}`);
    }
    seen.add(skill.name);
    skills.push(skill);
  }

  return skills;
}

function generateManifestCode(skills: Skill[]): string {
  const skillsJson = JSON.stringify(skills, null, 2);
  const skillNamesJson = JSON.stringify(
    skills.map((skill) => skill.name),
    null,
    2,
  );

  return `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by src/script/build-skills-manifest.ts
// Run 'bun run src/script/build-skills-manifest.ts' to regenerate

import type { Skill } from "./types";

export const SKILLS_MANIFEST: ReadonlyArray<Skill> = ${skillsJson} as const;

export const SKILL_NAME_VALUES = ${skillNamesJson} as const;

export type SkillName = (typeof SKILL_NAME_VALUES)[number];
`;
}

function main(): void {
  const skills = discoverSkills();
  const output = generateManifestCode(skills);
  writeFileSync(OUTPUT_FILE, output, "utf-8");

  console.log(`Generated: ${OUTPUT_FILE}`);
  console.log(`Skills: ${skills.length}`);
}

main();
