import { SKILL_NAMES } from "../constants.js";

export const PLAN_AGENT_AVAILABLE_SKILLS = [
  SKILL_NAMES.GIT_MASTER,
  SKILL_NAMES.DESIGN,
  SKILL_NAMES.CONVENTIONS,
  SKILL_NAMES.MAP_CODEBASE,
  SKILL_NAMES.JINN_EXPLORE,
  SKILL_NAMES.JINN_PROPOSE,
  SKILL_NAMES.JINN_TRIAGE,
];

export const DO_AGENT_AVAILABLE_SKILLS = [
  SKILL_NAMES.GIT_MASTER,
  SKILL_NAMES.DESIGN,
  SKILL_NAMES.CODE_QUALITY,
  SKILL_NAMES.JINN_CHECK,
  SKILL_NAMES.JINN_REVIEW,
  SKILL_NAMES.JINN_APPLY,
  SKILL_NAMES.JINN_SYNC,
  SKILL_NAMES.JINN_TRIAGE,
  SKILL_NAMES.JINN_UNBLOCK,
  SKILL_NAMES.JINN_READY_FOR_PROD,
  SKILL_NAMES.PROJECT_INIT,
  SKILL_NAMES.BUILD,
  SKILL_NAMES.DEPLOY,
  SKILL_NAMES.CONVENTIONS,
  SKILL_NAMES.MAP_CODEBASE,
];

export const CAPTURE_AGENT_AVAILABLE_SKILLS = [
  SKILL_NAMES.GIT_MASTER,
  SKILL_NAMES.JINN_ARCHIVE,
];

export const REVIEW_AGENT_AVAILABLE_SKILLS = [
  SKILL_NAMES.CODE_QUALITY,
  SKILL_NAMES.JINN_REVIEW,
  SKILL_NAMES.JINN_READY_FOR_PROD,
  SKILL_NAMES.GIT_MASTER,
];

export const ARCHITECT_AGENT_AVAILABLE_SKILLS = [
  SKILL_NAMES.CODE_QUALITY,
  SKILL_NAMES.CONVENTIONS,
  SKILL_NAMES.MAP_CODEBASE,
  SKILL_NAMES.JINN_READY_FOR_PROD,
];

export const DESIGNER_AGENT_AVAILABLE_SKILLS = [
  SKILL_NAMES.DESIGN,
  SKILL_NAMES.CODE_QUALITY,
];

export const GIT_AGENT_AVAILABLE_SKILLS = [SKILL_NAMES.GIT_MASTER];

export const SEARCH_AGENT_AVAILABLE_SKILLS = [
  SKILL_NAMES.GIT_MASTER,
  SKILL_NAMES.MAP_CODEBASE,
  SKILL_NAMES.JINN_EXPLORE,
];