import type { SkillTemplate } from "../../../core/templates/types.js";
import { parseFrontmatter } from "../../../core/templates/frontmatter.js";
import reactNativeSkillMarkdown from "./instructions.md";
import { SKILL_NAMES } from "../../constants.js";
import { getSkillReferences } from "../../.generated/templates.js";

export function getReactNativeSkillTemplate(): SkillTemplate {
  return {
    name: SKILL_NAMES.REACT_NATIVE,
    profile: "extended",
    description:
      "Guides React Native and Expo development across UI patterns, Expo Router conventions, styling, navigation, performance, animations, and state management. Use when building React Native screens, implementing mobile navigation, optimizing list performance, or when users ask about mobile UI, animations, or Expo configuration.",
    license: "MIT",
    compatibility: "React Native with Expo Router and Expo SDK.",
    metadata: {
      author: "project",
      version: "2.0",
      category: "Mobile",
      tags: [
        "react-native",
        "expo",
        "expo-router",
        "mobile",
        "performance",
        "animations",
        "reanimated",
        "lists",
        "navigation",
        "ios",
        "apple-hig",
      ],
    },
    when: [
      "user is building any React Native or Expo component, screen, or feature",
      "user is implementing Expo Router navigation, routes, tabs, or stacks",
      "user is styling a mobile UI following Apple HIG",
      "user is optimizing list, scroll, or rendering performance",
      "user is implementing animations with Reanimated or gestures",
      "user is working with native controls, media, storage, or device APIs",
      "user is configuring native modules, fonts, or Expo plugins",
      "user is structuring native dependencies in a monorepo",
    ],
    applicability: [
      "Use for all React Native and Expo app development",
      "Use when implementing any mobile UI, navigation pattern, or screen layout",
      "Use when reviewing mobile code for performance, correctness, or platform conventions",
    ],
    termination: [
      "Component or screen implemented following Expo Router and Apple HIG conventions",
      "Performance rules applied: FlashList, memoized items, stable callbacks",
      "Animations run on UI thread using transform/opacity only",
      "Native navigation stack used instead of JS navigators",
    ],
    outputs: [
      "React Native component or screen following Expo Router conventions",
      "Navigation layout with correct Stack, NativeTabs, and route structure",
      "Performance-optimized list implementation",
      "Animation using Reanimated on GPU-friendly properties",
    ],
    dependencies: [],
    references: getSkillReferences(
      SKILL_NAMES.REACT_NATIVE,
      // Expo Router & UI
      "references/expo-route-structure.md",
      "references/expo-animations.md",
      "references/expo-controls.md",
      "references/expo-form-sheet.md",
      "references/expo-gradients.md",
      "references/expo-icons.md",
      "references/expo-media.md",
      "references/expo-search.md",
      "references/expo-storage.md",
      "references/expo-tabs.md",
      "references/expo-toolbar-and-headers.md",
      "references/expo-visual-effects.md",
      "references/expo-webgpu-three.md",
      "references/expo-zoom-transitions.md",
      // Performance rules
      "references/animation-derived-value.md",
      "references/animation-gesture-detector-press.md",
      "references/animation-gpu-properties.md",
      "references/design-system-compound-components.md",
      "references/fonts-config-plugin.md",
      "references/imports-design-system-folder.md",
      "references/js-hoist-intl.md",
      "references/list-performance-callbacks.md",
      "references/list-performance-function-references.md",
      "references/list-performance-images.md",
      "references/list-performance-inline-objects.md",
      "references/list-performance-item-expensive.md",
      "references/list-performance-item-memo.md",
      "references/list-performance-item-types.md",
      "references/list-performance-virtualize.md",
      "references/monorepo-native-deps-in-app.md",
      "references/monorepo-single-dependency-versions.md",
      "references/navigation-native-navigators.md",
      "references/react-compiler-destructure-functions.md",
      "references/react-compiler-reanimated-shared-values.md",
      "references/react-state-dispatcher.md",
      "references/react-state-fallback.md",
      "references/react-state-minimize.md",
      "references/rendering-no-falsy-and.md",
      "references/rendering-text-in-text-component.md",
      "references/scroll-position-no-state.md",
      "references/state-ground-truth.md",
      "references/ui-expo-image.md",
      "references/ui-image-gallery.md",
      "references/ui-measure-views.md",
      "references/ui-menus.md",
      "references/ui-native-modals.md",
      "references/ui-pressable.md",
      "references/ui-safe-area-scroll.md",
      "references/ui-scrollview-content-inset.md",
      "references/ui-styling.md",
    ),
    instructions: parseFrontmatter(reactNativeSkillMarkdown).body,
  };
}
